export const PRODUCT_CATEGORY = "PRODUCT_CATEGORY"
export const PRODUCT_VIEW = "PRODUCT_VIEW"
export const PRODUCT_DETAILS = "PRODUCT_DETAILS"
export const PRODUCT_HOME= "PRODUCT_HOME"
export const PRODUCT_ADD_HOME="PRODUCT_ADD_HOME"


export const ADD_TO_CART= "ADD_TO_CART"
export const DELETE_FROM_CART= "DELETE_FROM_CART"
export const ADJUST_QUANTITY= "ADJUST_QUANTITY"
export const LOAD_QUANTITY= "LOAD_QUANTITY"